# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- main

pool:
  vmImage: 'windows-2022'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.0.x'
- task: PowerShell@2
  inputs:
    targetType: 'filePath'
    filePath: '$(Build.SourcesDirectory)/check-links.ps1'
    arguments: '"$(Build.SourcesDirectory)/README.md" "$(Build.SourcesDirectory)/ignore-urls.txt"'
    failOnStderr: true
    pwsh: true
- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: 'AILZ80ASM.Test\AILZ80ASM.Test.csproj'
    publishTestResults: false
