	RRC b,(ix+$11)
	RRC c,(ix+$22)
	RRC d,(ix+$33)
	RRC e,(ix+$44)
	RRC h,(ix+$55)
	RRC l,(ix+$66)
	RRC a,(ix+$77)
	NOP
	NOP
	NOP
	NOP
	RRC b,(iy+$11)
	RRC c,(iy+$22)
	RRC d,(iy+$33)
	RRC e,(iy+$44)
	RRC h,(iy+$55)
	RRC l,(iy+$66)
	RRC a,(iy+$77)
	NOP
	NOP
	NOP
	NOP

	RRC (ix+$11),b
	RRC (ix+$22),c
	RRC (ix+$33),d
	RRC (ix+$44),e
	RRC (ix+$55),h
	RRC (ix+$66),l
	RRC (ix+$77),a
	NOP
	NOP
	NOP
	NOP
	RRC (iy+$11),b
	RRC (iy+$22),c
	RRC (iy+$33),d
	RRC (iy+$44),e
	RRC (iy+$55),h
	RRC (iy+$66),l
	RRC (iy+$77),a
	NOP
	NOP
	NOP
	NOP