include "Test.inc"
	ORG	$8000
	ld a, TRUE
	;ld b, 0
	ld c, FALSE
include "Test1.inc"
	jp	LABEL
	DS  5

include ".\SubDir\Test3.bin", B
include ".\SubDir\Test3.bin", B, START
include ".\SubDir\Test3.bin", B, , LENGTH

include ".\SubDir\SubSubDir\TestSub.z80"
	LD HL, addr
addr: include "Test5.inc"

include ".\SubDir\Test3.bin", B, START, LENGTH
include ".\SubDir\Test3.bin", B, START - 4, LENGTH
