	org $8000

	DB " !\"#$%&\'()*+,-./"
	DB "0123456789:;<=>?"
	DB "@ABCDEFGHIJKLMNO"
	DB "PQRSTUVWXYZ[\\]^_"
	DB "`abcdefghijklmno"
	DB "pqrstuvwxyz{|}~\0"

	; 漢字テスト
	DB @SJIS:"国語算数理科社会"

	DB @JIS1:"国語算数理科社会"

	charmap @PPP, "Test.json"
	
	DB @PPP:"国語算数理科社会"

	; 文字列テスト	
	DB 'テスト'        ; SJISで変換、アセンブラのデフォルト値
	DB @JIS12:'テスト' ; JIS第一・二水準で変換
	DB @SJIS:'テスト'  ; SJISで変換

	DBFIL 14

	DB "テスト"        ; SJISで変換、アセンブラのデフォルト値
	DB @JIS12:"テスト" ; JIS第一・二水準で変換
	DB @SJIS:"テスト"  ; SJISで変換

	DBFIL 14

	charmap @PMW, "TestMW.json"

	DB @PMW:"ABC_CR_LF_ESC_{CRCR}_{CR}{LF}{ESC}"
