	RL b,(ix+$11)
	RL c,(ix+$22)
	RL d,(ix+$33)
	RL e,(ix+$44)
	RL h,(ix+$55)
	RL l,(ix+$66)
	RL a,(ix+$77)
	NOP
	NOP
	NOP
	NOP
	RL b,(iy+$11)
	RL c,(iy+$22)
	RL d,(iy+$33)
	RL e,(iy+$44)
	RL h,(iy+$55)
	RL l,(iy+$66)
	RL a,(iy+$77)
	NOP
	NOP
	NOP
	NOP

	RL (ix+$11),b
	RL (ix+$22),c
	RL (ix+$33),d
	RL (ix+$44),e
	RL (ix+$55),h
	RL (ix+$66),l
	RL (ix+$77),a
	NOP
	NOP
	NOP
	NOP
	RL (iy+$11),b
	RL (iy+$22),c
	RL (iy+$33),d
	RL (iy+$44),e
	RL (iy+$55),h
	RL (iy+$66),l
	RL (iy+$77),a
	NOP
	NOP
	NOP
	NOP