	SET B,  0, (IX+ 7)
	SET C,  1, (IX+ 6)
	SET D,  2, (IX+ 5)
	SET E,  3, (IX+ 4)
	SET H,  4, (IX+ 3)
	SET L,  5, (IX+ 2)
	SET A,  6, (IX+ 1)
	SET A,  7, (IX+ 0)

	SET B,  0, (IY+ 7)
	SET C,  1, (IY+ 6)
	SET D,  2, (IY+ 5)
	SET E,  3, (IY+ 4)
	SET H,  4, (IY+ 3)
	SET L,  5, (IY+ 2)
	SET A,  6, (IY+ 1)
	SET A,  7, (IY+ 0)

	SET 0, (IX+ 7), B  
	SET 1, (IX+ 6), C  
	SET 2, (IX+ 5), D  
	SET 3, (IX+ 4), E  
	SET 4, (IX+ 3), H  
	SET 5, (IX+ 2), L  
	SET 6, (IX+ 1), A  
	SET 7, (IX+ 0), A  

	SET 0, (IY+ 7), B  
	SET 1, (IY+ 6), C  
	SET 2, (IY+ 5), D  
	SET 3, (IY+ 4), E  
	SET 4, (IY+ 3), H  
	SET 5, (IY+ 2), L  
	SET 6, (IY+ 1), A  
	SET 7, (IY+ 0), A  