;--------------------------------------------------------------------
;AILZ80ASM ,X1turbo バンクメモリ対応(ROMモード)テスト
;
;note
; memory map
; output address    : CPU address   : section
; 0x0_0000-0_0x7FFF : 0x0000-0x7FFF : メインメモリ (#16)
; 0x0_8000-0_0xFFFF : 0x8000-0xFFFF : メインメモリ 
; 0x1_0000-0_1x7FFF : 0x0000-0x7FFF : バンクメモリ #0 
;
;バンクメモリ上のエントリアドレスは FAR_LABEL疑似型として、
;出力アドレス($$)の値を持たせて、出力アドレスから
;バンク番号と論理アドレスを取得する。

;--------------------------------------------------------------------
;バンクメモリ　サポートマクロ
BANK_MAIN	equ	0x10	;X1turboの仕様

;バンク番号（出力オフセット）を現状維持する ORG 疑似命令

;・マクロ内で $$ を参照するとエラーになる
;BORG	macro	__ADDR__
;	ORG	__ADDR__ , __ADDR__+($$ & 0xFF8000)
;	endm

;・アンダースコアの付いた引数(__ADDR__)が展開できない？
;BORG	macro	__ADDR__,__HERE__
;	ORG	__ADDR__ , __ADDR__+(__HERE__ & 0xFF8000)
;	endm

;引数で $$ を受け取っても参照できない
BORG	macro	ADDR,HERE
	ORG	ADDR , ADDR+(HERE & 0x000F8000)
	endm

;$$ を16bit値の範囲で受け取る
;ローカルラベルに事前定義
BORG2	macro	ADDR,HERE15
.here	equ	(HERE15*0x8000)
	ORG	ADDR,.here+ADDR
;	dw	HERE15		;verify OK
;	dw	.here/0x8000	;verify OK
	endm

;オフセット指定
BORG3	macro	ADDR,OFFSET
	ORG	ADDR,ADDR+OFFSET
	endm

;絶対指定
BORG4	macro	ADDR,OUTADDR
	ORG	ADDR,OUTADDR
	endm

;固定指定
BORG5	macro	ADDR
	ORG	ADDR,0x10000
	endm

;--------------------------------------------------------------------
;--------------------------------------------------------------------
;コモン
;・最初に0番地出力をしておかないとHEX形式出力でエラーになる？
	org	0x0000
	nop
;
;--------------------------------------------------------------------
;--------------------------------------------------------------------
;BANK #0 (0x0000-0x7FFF -> 0x10000-0x17FFF)
	org	0,0x00*0x8000 +0x10000	;BANK0の先頭アドレス
;テスト用の定義
ADDR:
.HERE	equ	$$
LBASE	equ	ADDR.HERE & 0xF8000
HERE	equ	$$
BASE	equ	(HERE & 0xF8000)
BASED	equ	0x10000
	nop
;
;--------------------------------------
;現在のオフセット（バンク)の任意アドレスに移動したい
	org	0,0x10000
	borg	0x0100,$$				;通らない
	nop
	org	0,0x10000
	borg	0x0101,HERE				;通らない
	nop
	org	0,0x10000
	borg2	0x0102,HERE/0x8000			;通らない
	nop
	org	0,0x10000
	borg3	0x0103,BASE				;通らない
	nop
	org	0,0x10000
	borg2	0x0104,2				;通らない
	nop
	org	0,0x10000
	borg4	0x0105,0x0104+BASE			;通らない
	nop
	org	0,0x10000
	borg4	0x0106,0x0105+BASED			;通らない
	nop
	org	0,0x10000
	borg4	0x0107,0x10107				;通らない
	nop
	org	0,0x10000
	borg5	0x0108					;通る
	nop
;

;
	org	0,0x10000
	org	0x0200,0x0200+($$ & 0xF8000)		;通る
	nop
	org	0,0x10000
	org	0x0201,0x0201+(ADDR.HERE & 0xF8000)		;通らない
	nop
	org	0,0x10000
	org	0x0202,0x0202+LBASE			;通らない
	nop
	org	0,0x10000
	org	0x0203,0x0203+(HERE & 0xF8000)		;通る
	nop
	org	0,0x10000
	org	0x0204,0x0204+BASE			;通る
	nop