	RR b,(ix+$11)
	RR c,(ix+$22)
	RR d,(ix+$33)
	RR e,(ix+$44)
	RR h,(ix+$55)
	RR l,(ix+$66)
	RR a,(ix+$77)
	NOP
	NOP
	NOP
	NOP
	RR b,(iy+$11)
	RR c,(iy+$22)
	RR d,(iy+$33)
	RR e,(iy+$44)
	RR h,(iy+$55)
	RR l,(iy+$66)
	RR a,(iy+$77)
	NOP
	NOP
	NOP
	NOP

	RR (ix+$11),b
	RR (ix+$22),c
	RR (ix+$33),d
	RR (ix+$44),e
	RR (ix+$55),h
	RR (ix+$66),l
	RR (ix+$77),a
	NOP
	NOP
	NOP
	NOP
	RR (iy+$11),b
	RR (iy+$22),c
	RR (iy+$33),d
	RR (iy+$44),e
	RR (iy+$55),h
	RR (iy+$66),l
	RR (iy+$77),a
	NOP
	NOP
	NOP
	NOP