
		ALLLD
		TestArg1 1			; 引数不一致
		TESTARG1 1, 2
		TestArg1 1, 2, 3	; 引数不一致
		ABC

ABC MACRO
		ld a,1
ENDM

ABC MACRO
		ld b,1
ENDM

ALLLD MACRO
[DEF]						; ローカルラベル以外不許可
		ld a,1
		ld b,2
ABC:	ld c,3				; ローカルラベル以外不許可
		ld d,4
		ld e,5
.LP		ld h,6
		ld l,7
ENDM

TestArg1 macro a1, a2
	ld a, a1
	ld b, a2
endm


TestArg macro a1,			; 引数が不完全
	ld a, a1
	ld b, a2
endm

LD macro a1, a2		; 使えない名前
	ld a, a1
	ld b, a2
endm

; 先頭が(は使えない
(DEF MACRO
		ld a,1
ENDM

; 先頭が)は使えない
)DEF MACRO
		ld a,1
MACROM

; 16進数は使えない
FFFFH MACRO
		ld a,1
ENDM

; 数値スタートは使えない
0START MACRO
		ld a,1
ENDM

NoEnd macro a1, a2
	ld a, a1
	ld b, a2