
LABEL_1		equ 1
LABEL_2		equ AAA

			LD A, LABEL_0
			LD A, LABEL_1
			LD A, LABEL_2
			LD A, (1+2))
			LD A, "ABCD"

LABEL_3		equ BBB

			ALIGN CCC
			ALIGN 16, DDD

			DS 6/0
			DS $10, EEE

			INCLUDE "E0003.Z80", B, FFF
			INCLUDE "E0003.Z80", B, 0, GGG

			DB AAA
			DW BBB

			DBFIL CCC
			DBFIL $10, DDD

			DWFIL EEE
			DWFIL $10, FFF

			TEST_M1 AAA
			TEST_M2 BBB
			TEST_M2 10

			REPT CCC
				XOR A
			ENDM

			REPT 8 LAST DDD
				XOR A
			ENDM

			LD A, ABS(EEE)

			#IF FFF
				XOR A
			#ENDIF

			ORG AAA
			ORG $1000, BBB


			TEST_M1 MACRO ARG1
				LD A, ARG1
				XOR A
			ENDM

			TEST_M2 MACRO ARG1
				LD A, ARG1 / AAA
				XOR A
			ENDM

			Function ABS(value) => value < 0 ? value * -1 : value

			LD A, %1111_0000
			LD A,  1111_0000b
			LD A, %1111_0000b
			LD A, %1112_0000
			LD A,  1111_0002b
			LD A, %1111_0000_1111

			LD B, 67o
			LD B, 68o
			LD B, 12o

			LD C, 12
			LD C, 255
			LD C, -1
			LD C, 12_3
			LD C, AB

			LD D, $34
			LD D, 34H
			LD D, 0x34
			LD D, $EF
			LD D, EFH
			LD D, 0xEF
			LD D, $FG
			LD D, FGH
			LD D, 0xFG
			LD D, $12H
			LD D, 0x12H

			LD E, "A"
			LD E, 'A'
			LD E, "AB"
			LD E, 'AB'
			LD E, "ABC"
			LD E, 'ABC'
			LD DE, 'AB'
			LD DE, "AB"
			LD DE, 'ABC'
			LD DE, "ABC"
