INCLUDE "Test.INC"

LB: REPEAT 3
        xor     a
END REPEAT

REPEAT 8 LAST -1
        ld      (hl), a
        set     5, h
        ld      (hl), a
        add     hl, de
END REPEAT

REPEAT 2
        xor     a

REPEAT 3
        LD      a, 0
END REPEAT

END REPEAT

REPEAT SCREEN.WIDTH
        RLA
END REPEAT

    JP LB

REPEAT 8 LAST -2
    ld b,8
.lp
    inc hl
    ld  a, (hl)
    cp  1
    jr nz, .break
    djnz .lp
.break

END REPEAT